ALTER TABLE categories ADD COLUMN IF NOT EXISTS season VARCHAR(50);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS flower VARCHAR(100);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS flower_icon VARCHAR(50);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS meaning VARCHAR(255);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image_url TEXT;
