CREATE TABLE IF NOT EXISTS provinces (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    code_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS wards (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    code_name VARCHAR(255),
    province_code VARCHAR(20) REFERENCES provinces(code)
);

CREATE INDEX IF NOT EXISTS idx_provinces_fullname ON provinces(full_name);
CREATE INDEX IF NOT EXISTS idx_wards_province ON wards(province_code);

-- Seed 63 provinces of Vietnam
INSERT INTO provinces (code, name, full_name, code_name) VALUES
('01', 'Hà Nội', 'Thành phố Hà Nội', 'ha_noi'),
('02', 'Hà Giang', 'Tỉnh Hà Giang', 'ha_giang'),
('04', 'Cao Bằng', 'Tỉnh Cao Bằng', 'cao_bang'),
('06', 'Bắc Kạn', 'Tỉnh Bắc Kạn', 'bac_kan'),
('08', 'Tuyên Quang', 'Tỉnh Tuyên Quang', 'tuyen_quang'),
('10', 'Lào Cai', 'Tỉnh Lào Cai', 'lao_cai'),
('11', 'Điện Biên', 'Tỉnh Điện Biên', 'dien_bien'),
('12', 'Lai Châu', 'Tỉnh Lai Châu', 'lai_chau'),
('14', 'Sơn La', 'Tỉnh Sơn La', 'son_la'),
('15', 'Yên Bái', 'Tỉnh Yên Bái', 'yen_bai'),
('17', 'Hòa Bình', 'Tỉnh Hòa Bình', 'hoa_binh'),
('19', 'Thái Nguyên', 'Tỉnh Thái Nguyên', 'thai_nguyen'),
('20', 'Lạng Sơn', 'Tỉnh Lạng Sơn', 'lang_son'),
('22', 'Quảng Ninh', 'Tỉnh Quảng Ninh', 'quang_ninh'),
('24', 'Bắc Giang', 'Tỉnh Bắc Giang', 'bac_giang'),
('25', 'Phú Thọ', 'Tỉnh Phú Thọ', 'phu_tho'),
('26', 'Vĩnh Phúc', 'Tỉnh Vĩnh Phúc', 'vinh_phuc'),
('27', 'Bắc Ninh', 'Tỉnh Bắc Ninh', 'bac_ninh'),
('30', 'Hải Dương', 'Tỉnh Hải Dương', 'hai_duong'),
('31', 'Hải Phòng', 'Thành phố Hải Phòng', 'hai_phong'),
('33', 'Hưng Yên', 'Tỉnh Hưng Yên', 'hung_yen'),
('34', 'Thái Bình', 'Tỉnh Thái Bình', 'thai_binh'),
('35', 'Hà Nam', 'Tỉnh Hà Nam', 'ha_nam'),
('36', 'Nam Định', 'Tỉnh Nam Định', 'nam_dinh'),
('37', 'Ninh Bình', 'Tỉnh Ninh Bình', 'ninh_binh'),
('38', 'Thanh Hóa', 'Tỉnh Thanh Hóa', 'thanh_hoa'),
('40', 'Nghệ An', 'Tỉnh Nghệ An', 'nghe_an'),
('42', 'Hà Tĩnh', 'Tỉnh Hà Tĩnh', 'ha_tinh'),
('44', 'Quảng Bình', 'Tỉnh Quảng Bình', 'quang_binh'),
('45', 'Quảng Trị', 'Tỉnh Quảng Trị', 'quang_tri'),
('46', 'Thừa Thiên Huế', 'Tỉnh Thừa Thiên Huế', 'thua_thien_hue'),
('48', 'Đà Nẵng', 'Thành phố Đà Nẵng', 'da_nang'),
('49', 'Quảng Nam', 'Tỉnh Quảng Nam', 'quang_nam'),
('51', 'Quảng Ngãi', 'Tỉnh Quảng Ngãi', 'quang_ngai'),
('52', 'Bình Định', 'Tỉnh Bình Định', 'binh_dinh'),
('54', 'Phú Yên', 'Tỉnh Phú Yên', 'phu_yen'),
('56', 'Khánh Hòa', 'Tỉnh Khánh Hòa', 'khanh_hoa'),
('58', 'Ninh Thuận', 'Tỉnh Ninh Thuận', 'ninh_thuan'),
('60', 'Bình Thuận', 'Tỉnh Bình Thuận', 'binh_thuan'),
('62', 'Kon Tum', 'Tỉnh Kon Tum', 'kon_tum'),
('64', 'Gia Lai', 'Tỉnh Gia Lai', 'gia_lai'),
('66', 'Đắk Lắk', 'Tỉnh Đắk Lắk', 'dak_lak'),
('67', 'Đắk Nông', 'Tỉnh Đắk Nông', 'dak_nong'),
('68', 'Lâm Đồng', 'Tỉnh Lâm Đồng', 'lam_dong'),
('70', 'Bình Phước', 'Tỉnh Bình Phước', 'binh_phuoc'),
('72', 'Tây Ninh', 'Tỉnh Tây Ninh', 'tay_ninh'),
('74', 'Bình Dương', 'Tỉnh Bình Dương', 'binh_duong'),
('75', 'Đồng Nai', 'Tỉnh Đồng Nai', 'dong_nai'),
('77', 'Bà Rịa - Vũng Tàu', 'Tỉnh Bà Rịa - Vũng Tàu', 'ba_ria_vung_tau'),
('79', 'Hồ Chí Minh', 'Thành phố Hồ Chí Minh', 'ho_chi_minh'),
('80', 'Long An', 'Tỉnh Long An', 'long_an'),
('82', 'Tiền Giang', 'Tỉnh Tiền Giang', 'tien_giang'),
('83', 'Bến Tre', 'Tỉnh Bến Tre', 'ben_tre'),
('84', 'Trà Vinh', 'Tỉnh Trà Vinh', 'tra_vinh'),
('86', 'Vĩnh Long', 'Tỉnh Vĩnh Long', 'vinh_long'),
('87', 'Đồng Tháp', 'Tỉnh Đồng Tháp', 'dong_thap'),
('89', 'An Giang', 'Tỉnh An Giang', 'an_giang'),
('91', 'Kiên Giang', 'Tỉnh Kiên Giang', 'kien_giang'),
('92', 'Cần Thơ', 'Thành phố Cần Thơ', 'can_tho'),
('93', 'Hậu Giang', 'Tỉnh Hậu Giang', 'hau_giang'),
('94', 'Sóc Trăng', 'Tỉnh Sóc Trăng', 'soc_trang'),
('95', 'Bạc Liêu', 'Tỉnh Bạc Liêu', 'bac_lieu'),
('96', 'Cà Mau', 'Tỉnh Cà Mau', 'ca_mau')
ON CONFLICT (code) DO NOTHING;
